### Find all content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content

### Create new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My Second blog post",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-10-07T19:42:24.228238265",
  "dateUpdated": null,
  "url": ""
}

### Update existing content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST!!!",
  "desc": "MY FIRST POST!!!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-10-07T19:42:24.228238265",
  "dateUpdated": "2023-10-07T19:42:24.228238265",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Update existing content with invalid id
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST!!!",
  "desc": "MY FIRST POST!!!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-10-07T19:42:24.228238265",
  "dateUpdated": "2023-10-07T19:42:24.228238265",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Delete existing content
DELETE http://localhost:8080/api/content/2